{
 "title": "sig",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Packet Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gossip_packets_received", "legendFormat": "gossip_packets_received" },
    { "expr": "gossip_packets_verified", "legendFormat": "gossip_packets_verified" },
    { "expr": "gossip_packets_processed", "legendFormat": "gossip_packets_processed" }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "idelta(ping_messages_dropped[$__interval])",
     "legendFormat": "ping_messages_dropped"
    },
    {
     "expr": "idelta(pull_requests_dropped[$__interval])",
     "legendFormat": "pull_requests_dropped"
    },
    {
     "expr": "idelta(prune_messages_dropped[$__interval])",
     "legendFormat": "prune_messages_dropped"
    }
   ]
  },
  {
   "title": "Message Type Recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "idelta(pull_requests_recv[$__interval])",
     "legendFormat": "pull_requests_recv"
    },
    {
     "expr": "idelta(pull_responses_recv[$__interval])",
     "legendFormat": "pull_responses_recv"
    },
    {
     "expr": "idelta(prune_messages_recv[$__interval])",
     "legendFormat": "prune_messages_recv"
    },
    {
     "expr": "idelta(push_messages_recv[$__interval])",
     "legendFormat": "push_messages_recv"
    },
    {
     "expr": "idelta(ping_messages_recv[$__interval])",
     "legendFormat": "ping_messages_recv"
    },
    {
     "expr": "idelta(pong_messages_recv[$__interval])",
     "legendFormat": "pong_messages_recv"
    }
   ]
  },
  {
   "title": "Message Type Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "idelta(ping_messages_sent[$__interval])",
     "legendFormat": "ping_messages_sent"
    },
    {
     "expr": "idelta(pong_messages_sent[$__interval])",
     "legendFormat": "pong_messages_sent"
    },
    {
     "expr": "idelta(prune_messages_sent[$__interval])",
     "legendFormat": "prune_messages_sent"
    },
    {
     "expr": "idelta(pull_requests_sent[$__interval])",
     "legendFormat": "pull_requests_sent"
    },
    {
     "expr": "idelta(pull_responses_sent[$__interval])",
     "legendFormat": "pull_responses_sent"
    },
    {
     "expr": "idelta(push_messages_sent[$__interval])",
     "legendFormat": "push_messages_sent"
    }
   ]
  },
  {
   "title": "Handle Messages Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "idelta(handle_batch_ping_time[$__interval])",
     "legendFormat": "handle_batch_ping_time"
    },
    {
     "expr": "idelta(handle_batch_pong_time[$__interval])",
     "legendFormat": "handle_batch_pong_time"
    },
    {
     "expr": "idelta(handle_batch_prune_time[$__interval])",
     "legendFormat": "handle_batch_prune_time"
    },
    {
     "expr": "idelta(handle_batch_pull_req_time[$__interval])",
     "legendFormat": "handle_batch_pull_req_time"
    },
    {
     "expr": "idelta(handle_batch_pull_resp_time[$__interval])",
     "legendFormat": "handle_batch_pull_resp_time"
    },
    {
     "expr": "idelta(handle_batch_push_time[$__interval])",
     "legendFormat": "handle_batch_push_time"
    },
    {
     "expr": "idelta(handle_trim_table_time[$__interval])",
     "legendFormat": "handle_trim_table_time"
    }
   ]
  },
  {
   "title": "Gossip Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "table_n_values", "legendFormat": "n_values" },
    { "expr": "table_n_pubkeys", "legendFormat": "n_pubkeys" }
   ]
  },
  {
   "title": "Push Message Processing Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "idelta(push_message_n_values[$__interval])",
     "legendFormat": "n_values"
    },
    {
     "expr": "idelta(push_message_n_failed_inserts[$__interval])",
     "legendFormat": "n_failed_inserts"
    },
    {
     "expr": "idelta(push_message_n_invalid_values[$__interval])",
     "legendFormat": "n_invalid_values"
    }
   ]
  },
  {
   "title": "Push Message Processing Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "idelta(push_messages_time_to_insert[$__interval])",
     "legendFormat": "time_to_insert"
    },
    {
     "expr": "idelta(push_messages_time_build_prune[$__interval])",
     "legendFormat": "time_build_prune"
    }
   ]
  }
 ]
}