{
 "title": "Geyser Metrics",
 "time": { "from": "2024-10-01T17:48:43.217Z", "to": "2024-10-01T17:54:09.377Z" },
 "panels": [
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(geyser_writer_total_bytes[$__rate_interval]) / 1000000",
     "legendFormat": "writer"
    },
    {
     "expr": "rate(geyser_reader_total_bytes[$__rate_interval]) / 1000000",
     "legendFormat": "reader"
    }
   ]
  },
  {
   "title": "Payloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "geyser_writer_n_payloads", "legendFormat": "writer_payloads" },
    { "expr": "geyser_reader_total_payloads", "legendFormat": "reader_payloads" }
   ]
  },
  {
   "title": "Reader Stalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(geyser_reader_pipe_empty_count[$__interval])",
     "legendFormat": "pipe_empty"
    }
   ]
  },
  {
   "title": "Write Stalls",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(geyser_writer_pipe_full_count[$__rate_interval])",
     "legendFormat": "pipe_full"
    },
    {
     "expr": "rate(geyser_writer_recycle_fba_empty_loop_count[$__rate_interval])",
     "legendFormat": "no_memory_available"
    }
   ]
  },
  {
   "title": "Reader State",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "geyser_reader_bincode_buf_size / 1000000",
     "legendFormat": "bincode_buf"
    },
    {
     "expr": "geyser_reader_io_buf_size / 1000000",
     "legendFormat": "io_buf"
    }
   ]
  }
 ]
}