global:
  scrape_interval: 2s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          # sig general
          - localhost:12345
          - host.docker.internal:12345
          # sig geyser
          - localhost:12355
          - host.docker.internal:12355
          # node-exporter
          - localhost:9100
          - host.docker.internal:9100
