global:
  scrape_interval: 2s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - host.docker.internal:12345 # sig prometheus general
          - host.docker.internal:12355 # sig prometheus geyser
          - node-exporter:9100 # node exporter
