global:
  scrape_interval: 2s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - host.docker.internal:12345