apiVersion: 1
groups:
  - orgId: 1
    editable: true
    name: sig-alert-evaluation-group
    folder: sig-alert-rule
    interval: 1m
    rules:
      - uid: ce8wwpcp2dkowb
        editable: true
        title: log-error-alert
        condition: C
        data:
          - refId: A
            queryType: range
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P8E80F9AEF21F6940
            model:
              datasource:
                type: loki
                uid: P8E80F9AEF21F6940
              editorMode: code
              expr: count_over_time({level="error"}[5m]) > 0
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: range
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: count
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 0s
        annotations:
          description: ""
          runbook_url: ""
          summary: ""
        labels:
          message: ""
        isPaused: false
        notification_settings:
          receiver: slack-sig-alerts
