apiVersion: 1
contactPoints:
  - orgId: 1
    name: slack-sig-alerts
    editable: true
    receivers:
      - uid: ae8wvbjn9bncxe
        type: slack
        settings:
          recipient: sig
          url: https://${SLACK_WEBHOOK_URL}
          text: |-
            {{ range .Alerts.Firing }}
              {{ .Annotations.summary }} -- {{ .PanelURL }}
            {{ end }}
          title: "{{ len .Alerts.Firing }} Alert(s) Firing"
        disableResolveMessage: false
