name: Proposals
description: Have an idea? Share it here!
labels: ["proposal"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A description of the problem you are facing.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: A description of how you want to solve the problem.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about your proposal.
