//! Generates decoded pubkey arrays for non-circulating supply accounts.
//!
//! Reads base58-encoded pubkeys from a .zon file, decodes them at build time,
//! and writes out a .zig file with pre-decoded `[32]u8` byte arrays.

const std = @import("std");
const base58 = @import("base58");

const PUBKEY_SIZE = 32;
const BASE58_ENDEC = base58.Table.BITCOIN;

const ZonData = struct {
    non_circulating_accounts: []const [:0]const u8,
    withdraw_authorities: []const [:0]const u8,
};

pub fn main() !void {
    var dba_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = dba_state.deinit();
    const gpa = dba_state.allocator();

    const argv = try std.process.argsAlloc(gpa);
    defer std.process.argsFree(gpa, argv);

    if (argv.len == 0) return error.EmptyArgv;
    const args = argv[1..];

    if (args.len == 0) return error.MissingOutputFileNameArg;
    const output_file_path = args[0];

    const zon: ZonData = @import("non-circulating-supply-zon");

    const output_file = try std.fs.cwd().createFile(output_file_path, .{});
    defer output_file.close();

    var buf: [65536]u8 = undefined;
    var fw = output_file.writer(&buf);
    const w = &fw.interface;

    try w.writeAll(
        \\//! DO NOT MODIFY: File generated by gen_non_circulating_supply.zig
        \\//!
        \\//! Pre-decoded pubkey byte arrays for non-circulating supply calculation.
        \\//!
        \\//! [agave] https://github.com/anza-xyz/agave/blob/v3.1.8/runtime/src/non_circulating_supply.rs
        \\
        \\
    );

    try emitArray(w, "non_circulating_accounts", zon.non_circulating_accounts);
    try w.writeByte('\n');
    try emitArray(w, "withdraw_authorities", zon.withdraw_authorities);
}

fn emitArray(w: anytype, name: []const u8, keys: []const [:0]const u8) !void {
    try w.print("pub const {s}: [{d}][32]u8 = .{{\n", .{ name, keys.len });

    for (keys) |key_str| {
        var decoded_buf: [base58.decodedMaxSize(base58.encodedMaxSize(PUBKEY_SIZE))]u8 = undefined;
        const decoded_len = BASE58_ENDEC.decode(&decoded_buf, key_str) catch |err| {
            std.log.err("Failed to decode pubkey '{s}': {s}", .{ key_str, @errorName(err) });
            return error.BadPubkey;
        };
        const decoded = decoded_buf[0..decoded_len];
        if (decoded.len != PUBKEY_SIZE) {
            std.log.err(
                "Pubkey '{s}' decoded to {d} bytes, expected {d}",
                .{ key_str, decoded_len, PUBKEY_SIZE },
            );
            return error.BadPubkey;
        }

        try w.writeAll("    .{");
        for (decoded, 0..) |byte, i| {
            if (i > 0) try w.writeAll(",");
            try w.print(" {d}", .{byte});
        }
        try w.writeAll(" },\n");
    }

    try w.writeAll("};\n");
    try w.flush();
}
