{
 "title": "Gossip",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Packets Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(gossip_valid_packets[$__rate_interval])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(gossip_invalid_packets[$__rate_interval])",
     "legendFormat": "invalid"
    }
   ]
  },
  {
   "title": "Messages Processed",
   "type": "barchart",
   "description": "Delta increase in the number of each message type processed per interval.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "delta(gossip_processed_messages[$__interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Values Discovered",
   "type": "barchart",
   "description": "Delta increase in the number of each discovered gossip value per interval.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "delta(gossip_discoveries[$__interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Messages Failed",
   "type": "barchart",
   "description": "Delta increase in the number of each message type failed per interval.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(gossip_invalid_messages[$__interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Table Size",
   "type": "barchart",
   "description": "Number of table entries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "gossip_table_entry_count", "legendFormat": "{{variant}}" }
   ]
  },
  { "title": "Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Messages Sent",
   "type": "barchart",
   "description": "Delta increase in the number of each message type pushed per interval.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "delta(gossip_pushed_messages[$__interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Values Sent",
   "type": "barchart",
   "description": "Delta increase in the number of each kind of pushed gossip value per interval.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "delta(gossip_pushed_values[$__interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  }
 ]
}