apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
