{
 "title": "AccountsDB Metrics",
 "time": { "from": "2024-08-26T19:40:11.380Z", "to": "2024-08-26T19:41:31.684Z" },
 "panels": [
  {
   "title": "Accounts (flush/cleaned/shrunk/deleted)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "number_files_flushed", "legendFormat": "flushed" },
    { "expr": "number_files_cleaned", "legendFormat": "cleaned" },
    { "expr": "number_files_shrunk", "legendFormat": "shrunk" },
    { "expr": "number_files_deleted", "legendFormat": "deleted" }
   ]
  },
  {
   "title": "Clean - Queued for deletion/shrink",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "clean_files_queued_deletion", "legendFormat": "Queued for deletion" },
    { "expr": "clean_files_queued_shrink", "legendFormat": "Queued for shrink" }
   ]
  },
  {
   "title": "Clean - reason for clean",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "clean_slot_old_state", "legendFormat": "Old state" },
    { "expr": "clean_slot_zero_lamports", "legendFormat": "Zero lamports" }
   ]
  },
  {
   "title": "Flush - Account file size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flush_account_file_size_bucket", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Clean - references deleted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "clean_references_deleted", "legendFormat": "References deleted" }
   ]
  },
  {
   "title": "Shrink - Account file shrunk by",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shrink_file_shrunk_by", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shrink - Accounts dead",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shrink_dead_accounts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shrink - Alive accounts",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shrink_alive_accounts", "legendFormat": "__auto" }
   ]
  }
 ]
}