{
 "title": "Message Handle Times",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prune Messages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_prune_time_bucket", "legendFormat": "{{label_name}}ms" }
   ]
  },
  {
   "title": "Push Messages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_push_time_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Pull Response",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "handle_batch_pull_resp_time_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "handle_batch_pull_req_time_bucket",
     "legendFormat": "{{le}}ms"
    }
   ]
  },
  {
   "title": "Ping Message Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_ping_time_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pong Handle",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_pong_time_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Trim Gossip Table",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_trim_table_time_bucket", "legendFormat": "__auto" }
   ]
  }
 ]
}