{
 "title": "Gossip Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Channel Lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "incoming_channel_length", "legendFormat": "incoming_channel_length" },
    { "expr": "verified_channel_length", "legendFormat": "verified_channel_length" },
    { "expr": "outgoing_channel_length", "legendFormat": "outgoing_channel_length" }
   ]
  },
  {
   "title": "Packet Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(gossip_packets_received_total[$__rate_interval])",
     "legendFormat": "gossip_packets_received_total"
    },
    {
     "expr": "rate(gossip_packets_verified_total[$__rate_interval])",
     "legendFormat": "gossip_packets_verified_total"
    },
    {
     "expr": "rate(gossip_packets_processed_total[$__rate_interval])",
     "legendFormat": "gossip_packets_processed_total"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "delta(ping_messages_dropped[$__interval])",
     "legendFormat": "ping_messages_dropped"
    },
    {
     "expr": "delta(pull_requests_dropped[$__interval])",
     "legendFormat": "pull_requests_dropped"
    },
    {
     "expr": "delta(prune_messages_dropped[$__interval])",
     "legendFormat": "prune_messages_dropped"
    }
   ]
  },
  {
   "title": "Message Type Recv",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(pull_requests_recv[$__interval])",
     "legendFormat": "pull_requests_recv"
    },
    {
     "expr": "delta(pull_responses_recv[$__interval])",
     "legendFormat": "pull_responses_recv"
    },
    {
     "expr": "delta(prune_messages_recv[$__interval])",
     "legendFormat": "prune_messages_recv"
    },
    {
     "expr": "delta(push_messages_recv[$__interval])",
     "legendFormat": "push_messages_recv"
    },
    {
     "expr": "delta(ping_messages_recv[$__interval])",
     "legendFormat": "ping_messages_recv"
    },
    {
     "expr": "delta(pong_messages_recv[$__interval])",
     "legendFormat": "pong_messages_recv"
    }
   ]
  },
  {
   "title": "Message Type Send",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(ping_messages_sent[$__interval])",
     "legendFormat": "ping_messages_sent"
    },
    {
     "expr": "delta(pong_messages_sent[$__interval])",
     "legendFormat": "pong_messages_sent"
    },
    {
     "expr": "delta(prune_messages_sent[$__interval])",
     "legendFormat": "prune_messages_sent"
    },
    {
     "expr": "delta(pull_requests_sent[$__interval])",
     "legendFormat": "pull_requests_sent"
    },
    {
     "expr": "delta(pull_responses_sent[$__interval])",
     "legendFormat": "pull_responses_sent"
    },
    {
     "expr": "delta(push_messages_sent[$__interval])",
     "legendFormat": "push_messages_sent"
    }
   ]
  },
  {
   "title": "Table Trim Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "table_pubkeys_dropped", "legendFormat": "table_pubkeys_dropped" },
    { "expr": "table_old_values_removed", "legendFormat": "table_old_values_removed" },
    { "expr": "table_trim_call_count", "legendFormat": "trim_call_count" },
    {
     "expr": "table_remove_old_values_call_count",
     "legendFormat": "remove_old_values_call_count"
    }
   ]
  },
  {
   "title": "Gossip Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "table_n_values", "legendFormat": "n_values" },
    { "expr": "table_n_pubkeys", "legendFormat": "n_pubkeys" }
   ]
  },
  {
   "title": "Push Message Processing Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "push_message_n_invalid_shred_version",
     "legendFormat": "invalid_shred_version"
    },
    { "expr": "push_message_n_new_inserts", "legendFormat": "new_inserts" },
    {
     "expr": "push_message_n_overwrite_existing",
     "legendFormat": "overwrites"
    },
    { "expr": "push_message_n_old_value", "legendFormat": "old_values" },
    { "expr": "push_message_n_duplicate_value", "legendFormat": "duplicate_values" },
    { "expr": "push_message_n_timeouts", "legendFormat": "timeouts" }
   ]
  },
  {
   "title": "Pull Response Processing Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pull_response_n_invalid_shred_version",
     "legendFormat": "invalid_shred_version"
    },
    { "expr": "pull_response_n_new_inserts", "legendFormat": "new_inserts" },
    {
     "expr": "pull_response_n_overwrite_existing",
     "legendFormat": "overwrites"
    },
    { "expr": "pull_response_n_old_value", "legendFormat": "old_values" },
    {
     "expr": "pull_response_n_duplicate_value",
     "legendFormat": "duplicate_values"
    },
    {
     "expr": "pull_response_n_duplicate_value",
     "legendFormat": "timeouts"
    }
   ]
  },
  {
   "title": "Pull Response : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "handle_batch_pull_resp_time_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Push : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_push_time_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Pong : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_pong_time_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ping : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_ping_time_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pull Request : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "handle_batch_pull_req_time_bucket",
     "legendFormat": "{{le}}ms"
    }
   ]
  },
  {
   "title": "Prune : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_batch_prune_time_bucket", "legendFormat": "{{label_name}}ms" }
   ]
  },
  {
   "title": "Trim Table : Handle Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "handle_trim_table_time_bucket", "legendFormat": "__auto" }
   ]
  }
 ]
}