{
 "title": "Turbine",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Shreds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(retransmit_shreds_received_count[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(retransmit_shreds_sent_count[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(retransmit_shred_byte_filtered_count[$__rate_interval])",
     "legendFormat": "shreds_byte_filtered"
    },
    {
     "expr": "rate(retransmit_shred_id_filtered_count[$__rate_interval])",
     "legendFormat": "shreds_shred_id_filtered"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "retransmit_receive_shreds_nanos",
     "legendFormat": "receive_shreds"
    },
    {
     "expr": "retransmit_dedup_and_group_shreds_nanos",
     "legendFormat": "dedup_and_group_shreds"
    },
    {
     "expr": "retransmit_create_and_send_retransmit_info_nanos",
     "legendFormat": "create_and_send_retransmit_info"
    },
    {
     "expr": "retransmit_get_slot_leader_nanos",
     "legendFormat": "get_slot_leader"
    },
    {
     "expr": "retransmit_get_turbine_tree_nanos",
     "legendFormat": "get_turbine_tree"
    },
    { "expr": "retransmit_shred_nanos", "legendFormat": "retransmit_shred" },
    { "expr": "retransmit_get_children_nanos", "legendFormat": "get_children" }
   ]
  },
  {
   "title": "Turbine Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "retransmit_level", "legendFormat": "retransmit_level" }
   ]
  },
  {
   "title": "Turbine Children",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "retransmit_children", "legendFormat": "children" },
    {
     "expr": "retransmit_children_with_addresses",
     "legendFormat": "children_with_addresses"
    }
   ]
  },
  {
   "title": "Deduper Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "retransmit_shred_byte_filter_saturated",
     "legendFormat": "byte_filter_saturated"
    },
    {
     "expr": "retransmit_shred_id_filter_saturated",
     "legendFormat": "shred_id_filter_saturated"
    }
   ]
  }
 ]
}