{
 "title": "Shred Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Shreds Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shred_processor_passed_to_inserter_count[$__rate_interval])",
     "legendFormat": "Passed to Inserter"
    },
    {
     "expr": "rate(shred_receiver_turbine_received_count[$__rate_interval])",
     "legendFormat": "Turbine Recv"
    },
    {
     "expr": "rate(shred_receiver_repair_received_count[$__rate_interval])",
     "legendFormat": "Repair Recv"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shred_tracker_finished_slots_through",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot Progression Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shred_tracker_finished_slots_through[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot Lag",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shred_tracker_max_slot_processed - shred_tracker_finished_slots_through - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shreds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(shred_receiver_received_count[$__rate_interval])",
     "legendFormat": "packets received"
    },
    {
     "expr": "rate(shred_receiver_turbine_received_count[$__rate_interval])",
     "legendFormat": "turbine received"
    },
    {
     "expr": "rate(shred_receiver_repair_received_count[$__rate_interval])",
     "legendFormat": "repair received"
    },
    {
     "expr": "rate(shred_receiver_satisfactory_shred_count[$__rate_interval])",
     "legendFormat": "shreds received"
    },
    {
     "expr": "rate(shred_verifier_received_count[$__rate_interval])",
     "legendFormat": "verifier received"
    },
    {
     "expr": "rate(shred_verifier_verified_count[$__rate_interval])",
     "legendFormat": "verified shreds"
    },
    {
     "expr": "rate(shred_processor_passed_to_inserter_count[$__rate_interval])",
     "legendFormat": "passed to inserter"
    }
   ]
  },
  {
   "title": "Repair Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "rate(repair_service_request_count[$__rate_interval])",
     "legendFormat": "repair requests"
    }
   ]
  },
  {
   "title": "Shred Verification Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(shred_verifier_fail_count[$__rate_interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Slot Progression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "shred_tracker_max_slot_processed",
     "legendFormat": "Max Detected"
    },
    {
     "expr": "shred_tracker_finished_slots_through",
     "legendFormat": "Completed Through"
    }
   ]
  },
  {
   "title": "Slot Progression Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(shred_tracker_finished_slots_through[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "shred_tracker_max_slot_processed - shred_tracker_finished_slots_through - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repair Batch Size Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(repair_service_batch_size_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repair Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "targets": [
    { "expr": "repair_service_last_batch_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Repair Batch Process Time Histogram",
   "type": "histogram",
   "description": "The amount of time it takes to generate and send a batch of repair requests",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(repair_service_batch_process_time_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repair Batch Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "repair_service_last_batch_process_time",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}