{
 "title": "Shred Collector",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Shred Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shred_processor_passed_to_inserter_count[$__rate_interval])",
     "legendFormat": "Processed"
    },
    {
     "expr": "rate(shred_receiver_turbine_received_count[$__rate_interval])",
     "legendFormat": "Turbine Recv"
    },
    {
     "expr": "rate(shred_receiver_repair_received_count[$__rate_interval])",
     "legendFormat": "Repair Recv"
    }
   ]
  },
  {
   "title": "Slot Progression",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shred_tracker_finished_slots_through[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shred_tracker_finished_slots_through",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shreds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(shred_receiver_received_count[$__rate_interval])",
     "legendFormat": "packets received"
    },
    {
     "expr": "rate(shred_receiver_turbine_received_count[$__rate_interval])",
     "legendFormat": "turbine received"
    },
    {
     "expr": "rate(shred_receiver_repair_received_count[$__rate_interval])",
     "legendFormat": "repair received"
    },
    {
     "expr": "rate(shred_receiver_satisfactory_shred_count[$__rate_interval])",
     "legendFormat": "shreds received"
    },
    {
     "expr": "rate(shred_verifier_received_count[$__rate_interval])",
     "legendFormat": "verifier received"
    },
    {
     "expr": "rate(shred_verifier_verified_count[$__rate_interval])",
     "legendFormat": "verified shreds"
    },
    {
     "expr": "rate(shred_processor_passed_to_inserter_count[$__rate_interval])",
     "legendFormat": "passed to inserter"
    }
   ]
  },
  {
   "title": "Slot Progression",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "shred_tracker_max_slot_processed",
     "legendFormat": "Max Detected"
    },
    {
     "expr": "shred_tracker_finished_slots_through",
     "legendFormat": "Completed Through"
    }
   ]
  },
  {
   "title": "Repair",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(repair_request_count[$__rate_interval])",
     "legendFormat": "repair requests"
    }
   ]
  },
  {
   "title": "Slot Progression Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(shred_tracker_finished_slots_through[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shred Verification Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(shred_verifier_fail_count[$__rate_interval])",
     "legendFormat": "{{variant}}"
    }
   ]
  }
 ]
}