{
 "title": "Transaction Sender Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Process Latencies (Millis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "transaction_sender_process_transactions_millis",
     "legendFormat": "processTransactions"
    },
    {
     "expr": "transaction_sender_retry_transactions_millis",
     "legendFormat": "retryTransactions"
    },
    {
     "expr": "transaction_sender_get_leader_addresses_millis",
     "legendFormat": "getLeaderAddresses"
    }
   ]
  },
  {
   "title": "Rpc Latencies (Millis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "transaction_sender_rpc_block_height_millis",
     "legendFormat": "getBlockHeight"
    },
    {
     "expr": "transaction_sender_rpc_signature_statuses_millis",
     "legendFormat": "getSignatureStatuses"
    }
   ]
  },
  {
   "title": "Total In / Out",
   "type": "timeseries",
   "description": "sent should equal received + retried",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(transaction_sender_received_count[5m])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(transaction_sender_sent_count[5m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(transaction_sender_retry_count[5m])",
     "legendFormat": "retried"
    }
   ]
  },
  {
   "title": "Transactions Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(transaction_sender_rooted_count[5m])",
     "legendFormat": "rooted"
    },
    {
     "expr": "rate(transaction_sender_failed_count[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "rate(transaction_sender_expired_count[5m])",
     "legendFormat": "expired"
    },
    {
     "expr": "rate(transaction_sender_exceeded_max_retries_count[5m])",
     "legendFormat": "exceeded_max_retries"
    }
   ]
  },
  {
   "title": "Transactions Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "transaction_sender_pending_count",
     "legendFormat": "transactions_pending"
    }
   ]
  },
  {
   "title": "Leaders Identified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "transaction_sender_leaders_identified_count",
     "legendFormat": "number_of_leaders_identified"
    }
   ]
  }
 ]
}