//! Generates the feature set ID constant.

const std = @import("std");
const base58 = @import("base58");

/// Information about a feature, including its name, pubkey, description, and status.
const ZonInfo = struct {
    name: [:0]const u8,
    pubkey: [:0]const u8,
    description: [:0]const u8,
    status: union(enum) {
        /// The feature has been removed from the feature set and its implementation has been removed from source.
        /// Fuzzing: reverted features may appear in historical regression fixtures.
        reverted,
        /// This feature is contained in the feature set and its implementation is not complete.
        /// Fuzzing: not advertised as a supported feature for fuzzing (i.e. it will not be toggled on).
        staged,
        /// This feature is contained in the feature set and its implementation is complete.
        /// Fuzzing: advertised as a supported feature for fuzzing (i.e. it may be toggled on and off).
        supported,
        /// This feature has been implemented and is included in the feature set.
        /// Fuzzing: advertised as a hardcoded feature for fuzzing (i.e. it is always toggled on).
        hardcoded,
        /// This feature has been implemented and is included in the feature set.
        /// Fuzzing: advertised as a hardcoded feature for fuzzing (i.e. it is always toggled on).
        persisted,
    },
    /// Optional note about the feature status. Required for all non-supported features,
    /// and may be provided for supported features to clarify their status or provide
    /// additional context.
    note: ?[:0]const u8 = null,
};

const PUBKEY_SIZE = 32;
const BASE58_ENDEC = base58.Table.BITCOIN;

pub fn main() !void {
    var dba_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = dba_state.deinit();
    const gpa = dba_state.allocator();

    const argv = try std.process.argsAlloc(gpa);
    defer std.process.argsFree(gpa, argv);

    if (argv.len == 0) return error.EmptyArgv;
    const args = argv[1..];
    if (args.len > 1) return error.TooManyArgs;

    const features: []const ZonInfo = @import("features");

    // Collect all runtime-supported pubkeys
    var pubkeys: [features.len][PUBKEY_SIZE]u8 = undefined;
    var pubkey_count: usize = 0;
    for (features) |feature| {
        switch (feature.status) {
            .reverted => continue,
            else => {},
        }
        const pubkey = &pubkeys[pubkey_count];
        var decoded_buf: [base58.decodedMaxSize(base58.encodedMaxSize(pubkey.len))]u8 = undefined;
        const decoded_len = BASE58_ENDEC.decode(&decoded_buf, feature.pubkey) catch |err| {
            std.log.err(
                "Failed to decode pubkey '{s}' for feature '{s}': {s}",
                .{ feature.pubkey, feature.name, @errorName(err) },
            );
            return error.BadPubkey;
        };
        const decoded = decoded_buf[0..decoded_len];
        if (decoded.len != pubkey.len) {
            std.log.err(
                (
                    \\Failed to decode pubkey '{s}' for feature '{s}': invalid length '{d}' when decoded (expected length {d}).
                    \\Decoded result: '{f}'.
                ),
                .{
                    feature.pubkey,
                    feature.name,
                    decoded_len,
                    pubkey.len,
                    std.zig.fmtString(decoded),
                },
            );
            return error.BadPubkey;
        }
        pubkey.* = decoded[0..pubkey.len].*;
        pubkey_count += 1;
    }

    const included_pubkeys = pubkeys[0..pubkey_count];

    // Sort pubkeys lexicographically
    std.mem.sort([PUBKEY_SIZE]u8, included_pubkeys, {}, struct {
        fn lessThan(_: void, a: [PUBKEY_SIZE]u8, b: [PUBKEY_SIZE]u8) bool {
            return std.mem.order(u8, &a, &b) == .lt;
        }
    }.lessThan);

    // Hash all pubkeys
    var hasher = std.crypto.hash.sha2.Sha256.init(.{});
    for (included_pubkeys) |pk| {
        hasher.update(&pk);
    }
    const feature_set_id = std.mem.readInt(
        u32,
        hasher.finalResult()[0..4],
        .little,
    );

    if (args.len == 0) {
        var stdout_buffer: [64]u8 = undefined;
        var stdout_writer = std.fs.File.stdout().writer(&stdout_buffer);
        const stdout = &stdout_writer.interface;
        try stdout.print("FEATURE_SET_ID: {d}\n", .{feature_set_id});
        try stdout.flush();
        return;
    }

    const output_file_path = args[0];

    const output_file = try std.fs.cwd().createFile(output_file_path, .{});
    defer output_file.close();

    var output_buf: [4096]u8 = undefined;
    var output_fw = output_file.writer(&output_buf);
    const output_w = &output_fw.interface;
    try output_w.print(
        \\//! DO NOT MODIFY: File generated by gen_feature_set_id.zig
        \\//!
        \\//! The feature set identifier - first 4 bytes of SHA256 hash of all known feature pubkeys (sorted).
        \\//! This is used for client compatibility checks.
        \\//!
        \\//! [agave] https://github.com/anza-xyz/agave/blob/01159e4643e1d8ee86d1ed0e58ea463b338d563f/feature-set/src/lib.rs#L2318
        \\
        \\pub const FEATURE_SET_ID: u32 = {d};
        \\
    , .{feature_set_id});
    try output_w.flush();
}
