name: Performance regression check
on:
  push:
    branches:
      - master
      - 19/benchmarks-ci

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      # run benchmarks
      - name: benchmarks
        run: zig build -Doptimize=ReleaseSafe benchmark -- --metrics
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: "customSmallerIsBetter"
          # Where the output from the benchmark tool is stored
          output-file-path: results/output.txt
          # Where the previous data file is stored
          external-data-json-path: ./cache/benchmark-data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
      # Upload the updated cache file for the next job by actions/cache
